name: Build and Release Android App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Decode Keystore
      run: |
        echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 -d > ./Android/app/my-release-key.keystore
        ls -l ./Android/app/ # List to verify the file is there

    - name: Set execution flag for gradlew
      run: chmod +x ./Android/gradlew

    - name: Build Release APK
      run: |
        cd Android
        ./gradlew assembleRelease \
          -PsigningKeyStorePath=./app/my-release-key.keystore \
          -PsigningStorePassword=${{ secrets.SIGNING_STORE_PASSWORD }} \
          -PsigningKeyAlias=${{ secrets.SIGNING_KEY_ALIAS }} \
          -PsigningKeyPassword=${{ secrets.SIGNING_KEY_PASSWORD }} \
          --stacktrace

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: ./Android/app/release/app-release.apk

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: ./Android/app/release/app-release.apk
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}