name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: "8"
      
      - name: Set execution flag for gradlew
        run: chmod +x Android/gradlew
      
      - name: Build APK
        run: cd Android && ./gradlew assembleDebug --stacktrace
    
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: Android/app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v2
        with:
          name: apk
      
      # Removed the listing step as we now know the APK is in the root
      
      - name: Verify APK Presence
        run: |
          if [ -f app-debug.apk ]; then
            echo "APK exists, proceeding with release."
          else
            echo "APK does not exist, halting workflow."
            exit 1
          fi
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: app-debug.apk  # Adjusted to reflect the correct path
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.event.repository.name }} v${{ github.ref_name }}
